---
title: "Final Project"
author: "Sophia Puliatti"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---


**New Introduction** 

San Francisco sand dunes have not been in their native state for over 100 years, but in the past 30 years the Presidio Trust has worked to restore them. These sand dunes were formerly inhabited by the Xerces blue butterfly (*Glaucopsyche xerces*) that went extinct in the 1940’s. In the Presidio Trust’s efforts to restore the dunes, they began to reintroduce native animals to the ecosystem. The Xerces butterfly is nearly genetically identical to the Silvery blue butterfly (*Glaucopsyche lygdamus*) and in the past few years the Presidio Trust and the California Academy of Sciences have been collaborating to release Silvery blue butterflies into the Presidio to fulfill the Xerces niche. While the two butterflies have the same host plant and theoretically fulfill the same niche, it is unclear if the Silvery blue can or will successfully establish in the restored dunes. These butterflies are collected from Monterey county and released days after population peak in the hopes of bringing fertilized females to the Presidio. This process of releasing has been done every year since 2024, with monitoring for presence of Silvery blue before and after releases. My research aims at understanding the relationship between time of season, temperature, and genetics on the success of survival. Taking the data from previous years of Silvery blue releases combined with the current seasons data, I will compare environmental conditions to the number of sightings of butterflies seen after release. Tracking this survival rate is an indication of success for each release. During the release process we collect small parts of their wings for genetic analysis. In the following spring we capture any Silvery blues found in the dunes and collect small samples from their wings to run genetic analysis and compare them to the butterflies released in the previous year. The combination of reproductive success,  microclimate preference, and butterfly genetics provides insight on the success of the San Francisco Presidio dune restoration. 

 

***Research question:***

Are the sand dunes in San Francisco Presidio restored enough for *Glaucopsyche lygdamus* to successfully fill the *Glaucopsyche xerces* niche? 

Aim 1: What is the survival rate of *Glaucopsyche lygdamus* following release?
Aim 2. What makes the *Glaucopsyche lygdamus* reside and engage with particular parts of the release sight?
